Heyday\MenuManager\MenuItem:
  extensions:
    - Marketo\Heyday\MenuItemSquared

Heyday\MenuManager\MenuAdmin:
  extensions:
    - Marketo\Heyday\MenuSetSquared

Heyday\MenuManager\MenuSet:
  extensions:
    - Marketo\Heyday\MenuSetSquared
